# Generated by Django 2.2.10 on 2020-03-23 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('biography', models.TextField(max_length=2048, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actor_images', verbose_name='Фото')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('biography', models.TextField(max_length=2048, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='director_images', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название фильма')),
                ('description', models.TextField(max_length=2048, verbose_name='Описание фильма')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(999)], verbose_name='Длительность фильма')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=5, verbose_name='Страна выпуска')),
                ('photo', models.ImageField(upload_to='movie_images', verbose_name='Постер к фильму')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_taken', to='webapp.Movie', verbose_name='Связь к фильму')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Связь к пользователю')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='webapp.Genre', verbose_name='Связь к жанру')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='webapp.Movie', verbose_name='Связь к фильму')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_at', to='webapp.Director', verbose_name='Связь к режиссеру')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_by', to='webapp.Movie', verbose_name='Связь к фильму')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acted_at', to='webapp.Actor', verbose_name='Связь к автору')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acted_by', to='webapp.Movie', verbose_name='Связь к фильму')),
            ],
        ),
    ]
