# Generated by Django 2.2.10 on 2020-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(default='-', max_length=1024, verbose_name='Текст отзыва'),
        ),
    ]
