# Generated by Django 2.2.10 on 2020-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rating_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Идентификация'),
        ),
    ]
